github actions bos loader checksum verification

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -33,7 +33,14 @@ jobs:
       - name: Install dependencies
         run: |
           npm ci
-          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/mpeterdev/bos-loader/releases/download/v0.7.1/bos-loader-v0.7.1-installer.sh | sh
+          curl --proto '=https' --tlsv1.2 -LsSf -o bos-loader.sh https://github.com/mpeterdev/bos-loader/releases/download/v0.7.1/bos-loader-v0.7.1-installer.sh
+          echo "88865badedb06428b9cad09f11650eb038b1729fb3409842e4b01859cb0b3497 bos-loader.sh" | sha256sum --check
+          if [ $? -eq 0 ]; then
+            sh bos-loader.sh
+          else
+            echo "Checksum verification failed."
+            exit 1
+          fi
           npx playwright install-deps
           npx playwright install
       - name: Run tests
